[build]
  # Install dependencies and build the app
  command = "cd web && npm install && npm run build"
  publish = "web/build"

# Define build settings
# More information: https://docs.netlify.com/configure-builds/environment-variables/
[build.environment]
  NODE_ENV = "production"

# Define the redirect rules
# More information: https://docs.netlify.com/routing/redirects/

[[redirects]]
  from = "/api/hello"
  to = "${REACT_APP_HELLO_API_URL}"
  status = 200

[[redirects]]
  from = "/*"
  to = "/web/index.html"
  status = 200
