[build]
  # Install dependencies and build the app
  command = "npm install && ln -s node_modules ./web/node_modules && npm run build:web"
  publish = "build"

[build.environment]
  NODE_ENV = "production"
  
[[redirects]]
  from = "/api/hello"
  to = "/api-mock/hello.txt"
  status = 200