name: Build and Deploy Express App using SSH

on:
  push:
    branches: [pre-bit]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install npm dependencies
        working-directory: ./api
        run: npm install
      
      - name: Build the app
        working-directory: ./api
        run: npm run build --if-present
      
      - name: Copy code to server
        uses: appleboy/scp-action@v1.0.4
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "api/"
          target: "/projects/api/"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /projects/api/
            npm install
            npm run start

