name: Build and Deploy Express App using SSH

on:
  push:
    branches: [pre-bit]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install npm dependencies
        working-directory: ./api
        run: npm install
      
      - name: Build the app
        working-directory: ./api
        run: npm run build --if-present
      
      
      - name: Copy API to Remote Server
        uses: easingthemes/ssh-deploy@v2.1.5
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          server: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          port: 22
          source: ./api
          target: /projects/api


