name: Build and Deploy Express App using SSH

on:
  push:
    branches: [pre-bit]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
      
      - name: Install npm dependencies
        working-directory: ./api
        run: npm install
      
      - name: Build the app
        working-directory: ./api
        run: npm run build --if-present
      
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            cd /api
            mkdir api
            cd api
            cp -r ../../api .
            npm install
            npm run start
